# Generated by Django 2.2 on 2019-11-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default='Required', max_length=254),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='Required', max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('S', 'Shipping')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SC', 'Skin Care'), ('AA', 'Anti Aging'), ('HP', 'Hair Products'), ('SP', 'Slimming Products'), ('SL', 'Skin Lightening')], max_length=2),
        ),
    ]
